project_name_override: nadag-innmelding-python-client
package_name_override: nadag_innmelding_python_client
package_version_override: 1.0-rc.1
post_hooks:
  # - "bash -c 'cd field-manager-python-client && poetry install'"
