from enum import StrEnum


class GeotekniskStoppkode(StrEnum):
    ANTATTBERG = "ANTATTBERG"
    ANTATTSTEINBLOKK = "ANTATTSTEINBLOKK"
    BRUDDBORSTANGSPISS = "BRUDDBORSTANGSPISS"
    DYBDEIBERGOPPNÅDD = "DYBDEIBERGOPPNÅDD"
    DYBDEIFJELLMERENN3METER = "DYBDEIFJELLMERENN3METER"
    DYBDEIFJELLMERENN3METERMEDANALYSE = "DYBDEIFJELLMERENN3METERMEDANALYSE"
    KJERNEBORINGMERENN3METER = "KJERNEBORINGMERENN3METER"
    MATERIALELLERMASKINFEIL = "MATERIALELLERMASKINFEIL"
    SONDERINGAVBRUTT = "SONDERINGAVBRUTT"
    SONDERINGAVBRUTTFASTGRUNN = "SONDERINGAVBRUTTFASTGRUNN"
    SONDERINGAVSLUTTETUTENSTOPP = "SONDERINGAVSLUTTETUTENSTOPP"
    STEINBLOKKFJELL = "STEINBLOKKFJELL"
    USPESIFISERT = "USPESIFISERT"

    def __str__(self) -> str:
        return str(self.value)
