from enum import StrEnum


class NADAGDokumentType(StrEnum):
    ANDRE_VEDLEGG_TIL_BOREHULL = "ANDRE_VEDLEGG_TIL_BOREHULL"
    BILDE = "BILDE"
    BILDE_BOREHULLSPROFIL = "BILDE_BOREHULLSPROFIL"
    BILDE_KOBLET_TIL_DIGITALISERT_DWG_TEGNING = "BILDE_KOBLET_TIL_DIGITALISERT_DWG_TEGNING"
    DIGITALISERT_DWG_TEGNING = "DIGITALISERT_DWG_TEGNING"
    GEOTEKNISK_RAPPORT = "GEOTEKNISK_RAPPORT"
    LABRAPPORT = "LABRAPPORT"
    MODELL = "MODELL"
    OPPTEGNINGSSYMBOL = "OPPTEGNINGSSYMBOL"
    PLANTEGNING = "PLANTEGNING"
    PROFILTEGNING = "PROFILTEGNING"
    RÅDATAFIL = "RÅDATAFIL"
    TEGNING = "TEGNING"
    USPESIFISERT_DOKUMENTTYPE = "USPESIFISERT_DOKUMENTTYPE"
    VURDERINGSRAPPORT = "VURDERINGSRAPPORT"

    def __str__(self) -> str:
        return str(self.value)
